"""empty message

Revision ID: ba168df44dec
Revises: 
Create Date: 2022-12-04 14:25:16.249671

"""


# revision identifiers, used by Alembic.
revision = "ba168df44dec"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
